import type { Metadata } from "next";
import localFont from 'next/font/local'
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import StoreProvider from '@/app/StoreProvider';
import Header from '@/components/Header';

const gilroy = localFont({
	src: [
		{
			path: '../../public/fonts/Gilroy-Regular.woff',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/Gilroy-SemiBold.woff',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../../public/fonts/Gilroy-Bold.woff',
			weight: '700',
			style: 'normal',
		},
	],
})

import '../colors.css';
import '../globals.css';

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: [
		{
			rel: 'icon',
			type: 'image/png',
			url: '/favicon-48x48.png',
			sizes: '48x48',
		},
		{
			rel: 'icon',
			type: 'image/svg+xml',
			url: '/favicon.svg',
		},
		{
			rel: 'shortcut icon',
			url: '/favicon.ico',
		},
		{
			rel: 'apple-touch-icon',
			sizes: '180x180',
			url: '/apple-touch-icon.png'
		},
		{
			rel: 'manifest',
			url: '/site.webmanifest',
		}
	]
};

export default async function RootLayout(
	{
		children,
		params: { locale },
	}: Readonly<{
		children: React.ReactNode;
		params: { locale: string };
	}>) {
	const messages = await getMessages();

	return (
		<html lang={ locale }>
		<body className={ gilroy.className }>
		<StoreProvider>
			<NextIntlClientProvider messages={ messages }>
				<Header locale={ locale } />
				{ children }
			</NextIntlClientProvider>
		</StoreProvider>
		</body>
		</html>
	);
};
